import fs from "fs";
import path from "path";
import zlib from "zlib";
import matter from "gray-matter";
import { marked } from "marked";
export interface StoreUseCase {
  id: string;
  description: string;
  category: string;
  featuresUsed: string[];
  chunkContent?: string;
  vector?: number[];
  distance?: number;
}
import { replaceMacros } from "../lib/macros.ts";
import { scanAllGuides, type GuideInventory } from "../../lib/guide-validation.ts";
import { getFeatureName } from "../lib/baseline.ts";

const ROOT_DIR = path.resolve(import.meta.dirname, "..");
const BUILD_GUIDES_DIR = path.join(ROOT_DIR, "build/guides");
const OUTPUT_FILE = path.join(ROOT_DIR, "lib/use-cases.gen.ts");

interface UseCase {
  id: string;
  description: string;
  category: string;
  featuresUsed: string[];
}

async function processGuides() {
  const targetGuidePath = process.argv.slice(2).find(arg => !arg.startsWith("--"));
  const force = process.argv.includes("--force");

  // Scan guides first to see if we even need to run
  let readyGuides = scanAllGuides().filter(inv => inv.hasGuide);

  const VECTORS_FILE = path.join(ROOT_DIR, "lib/use-cases.vectors.gen.json.gz");

  if (!targetGuidePath && !force && fs.existsSync(OUTPUT_FILE) && fs.existsSync(BUILD_GUIDES_DIR) && fs.existsSync(VECTORS_FILE)) {
    const outputFileMTime = Math.min(
      fs.statSync(OUTPUT_FILE).mtimeMs,
      fs.statSync(VECTORS_FILE).mtimeMs
    );
    let anyGuideNewer = false;

    if (fs.statSync(import.meta.filename).mtimeMs > outputFileMTime) {
      anyGuideNewer = true;
    } else {
      for (const inv of readyGuides) {
        const guidePath = path.join(inv.dir, "guide.md");
        if (fs.existsSync(guidePath) && fs.statSync(guidePath).mtimeMs > outputFileMTime) {
          anyGuideNewer = true;
          break;
        }
      }
    }

    if (!anyGuideNewer) {
      // No guides or script modified since last build. Skipping guide build
      console.log("👌");
      return;
    }
  }

  // Ensure clean build/guides exists
  if (fs.existsSync(BUILD_GUIDES_DIR)) {
    fs.rmSync(BUILD_GUIDES_DIR, { recursive: true, force: true });
  }
  fs.mkdirSync(BUILD_GUIDES_DIR, { recursive: true });

  const useCases: UseCase[] = [];
  const storeUseCases: StoreUseCase[] = [];

  console.log("Initializing Embedder...");
  const modelArg = process.argv.find((arg) => arg.startsWith("--model="));
  const modelName = modelArg ? modelArg.split("=")[1] : undefined;
  
  if (modelName) {
    console.log(`Using custom embedding model: ${modelName}`);
  }
  
  const { Embedder } = await import("../lib/transformers-embedder.ts");
  const embedder = Embedder.getInstance(modelName);
  await embedder.init();

  if (targetGuidePath) {
    // Single guide mode
    const absoluteTargetPath = path.resolve(ROOT_DIR, "..", targetGuidePath);
    console.log(`Building single guide from: ${absoluteTargetPath}`);

    const guidePath = path.join(absoluteTargetPath, "guide.md");
    if (!fs.existsSync(guidePath)) {
      throw new Error(`guide.md not found in ${absoluteTargetPath}.`);
    }

    const category = path.basename(path.dirname(absoluteTargetPath));
    const name = path.basename(absoluteTargetPath);
    readyGuides = [{dir: absoluteTargetPath, name, category, hasGuide: true} as GuideInventory];
  }

  console.log("Generating embeddings…");
  for (const inv of readyGuides) {
    const guidePath = path.join(inv.dir, "guide.md");
    await processSingleGuideFile(guidePath, inv.category, inv.name, useCases, storeUseCases, embedder);
  }

  // Generate TypeScript file
  const tsContent = `// This file is auto-generated by scripts/build-guides.ts
export interface UseCase {
  id: string;
  description: string;
  category: string;
  featuresUsed: string[];
}

export const USE_CASES: UseCase[] = ${JSON.stringify(useCases, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`Generated ${useCases.length} use cases to ${OUTPUT_FILE}`);


  const jsonContent = JSON.stringify(storeUseCases);
  const compressed = zlib.gzipSync(jsonContent);
  fs.writeFileSync(VECTORS_FILE, compressed);
  console.log(`Vector storage updated at ${VECTORS_FILE}`);

}

export function chunkMarkdown(markdown: string): string[] {
  const tokens = marked.lexer(markdown);
  const chunks: string[] = [];
  let currentChunk: string[] = [];

  for (const token of tokens) {
    if (token.type === 'heading') {
      if (currentChunk.length > 0) {
        chunks.push(currentChunk.join("\n\n"));
        currentChunk = [];
      }
      currentChunk.push(token.raw);
    } else {
      currentChunk.push(token.raw);
    }
  }

  if (currentChunk.length > 0) {
    chunks.push(currentChunk.join("\n\n"));
  }

  return chunks.filter(chunk => chunk.trim().length > 0);
}

async function processSingleGuideFile(
  filePath: string,
  category: string,
  id: string,
  useCases: UseCase[],
  storeUseCases: StoreUseCase[],
  embedder: any
) {
  const content = fs.readFileSync(filePath, "utf-8");
  const { data, content: markdownBody, matter: frontmatter } = matter(content, {});

  if (!data.description || !frontmatter) {
    throw new Error(`Missing frontmatter or description in ${filePath}`);
  }

  if (markdownBody.trim().length === 0) {
    // Just a stub guide. No content to index.
    return;
  }

  const processedMarkdown = replaceMacros(markdownBody, filePath);

  const featureIds: string[] = data['web-feature-ids'] || [];
  const featuresUsed = featureIds.map(getFeatureName);

  useCases.push({
    id,
    description: data.description,
    category,
    featuresUsed,
  });

  const isNoChunking = process.argv.includes("--no-chunking");
  const chunks = isNoChunking 
    ? [`${frontmatter}\n\n${processedMarkdown}`] 
    : [...chunkMarkdown(processedMarkdown), frontmatter];

  for (const chunk of chunks) {
    const embeddingText = `${id} (${category})\n\n${chunk}`;
    const vector = await embedder.embed(embeddingText);

    storeUseCases.push({
      id,
      description: data.description,
      category,
      featuresUsed,
      chunkContent: chunk,
      vector
    });
  }

  // Create category dir in build/guides
  const buildCategoryDir = path.join(BUILD_GUIDES_DIR, category);
  if (!fs.existsSync(buildCategoryDir)) {
    fs.mkdirSync(buildCategoryDir, { recursive: true });
  }

  // Write clean markdown to build dir
  const buildFilePath = path.join(buildCategoryDir, `${id}.md`);
  fs.writeFileSync(buildFilePath, processedMarkdown.trimStart());
}

// Only run automatically if executed directly
if (process.argv[1] === import.meta.filename) {
  processGuides().catch(console.error);
}
