// This file is auto-generated by scripts/build-guides.ts
export interface UseCase {
  id: string;
  description: string;
  category: string;
}

export const USE_CASES: UseCase[] = [
  {
    "id": "image-to-text",
    "description": "Turn images into text, captions, or structured data using the built-in Prompt API",
    "category": "ai"
  },
  {
    "id": "carousel",
    "description": "Build responsive, accessible carousels with CSS Scroll Snap",
    "category": "ui"
  },
  {
    "id": "tooltip",
    "description": "Create tooltips with Popover API and Interest Invokers",
    "category": "ui"
  },
  {
    "id": "break-long-tasks",
    "description": "Improve interaction responsiveness (INP) by yielding to the main thread.",
    "category": "webperf"
  },
  {
    "id": "lazy-load-images",
    "description": "Defer loading of off-screen images to minimize network contention and improve LCP.",
    "category": "webperf"
  },
  {
    "id": "preload-prerender",
    "description": "Improve navigation speed by preloading key resources or prerendering pages before the user clicks.",
    "category": "webperf"
  }
];
