import { glob } from "glob";
import path from 'path';
import fs from 'fs';
import { collectGuidesUsed, collectGuidanceToolsUsed } from './guidance_validation.ts';
import { Agents, type SuiteConfig } from '../config.ts';
import { getTaskMap } from '../../lib/guide-validation.ts';
import { extractGeminiCliModel } from '../agents/gemini-cli-agent.ts';
import { extractClaudeCodeModel } from '../agents/claude-code-agent.ts';
import { extractCodexCliModel } from '../agents/codex-cli-agent.ts';
import { getGraderScriptContent } from './agent-shared.ts';

function isTargetAppPresent(targetFile: string, targetPkgJson: string): boolean {
  return fs.existsSync(targetFile) || fs.existsSync(targetPkgJson);
}

export function extractModelFromResults(resultsDir: string, agent: string): string {
  if (agent === Agents.GEMINI_CLI) {
    return extractGeminiCliModel(resultsDir);
  } else if (agent === Agents.CLAUDE_CODE) {
    return extractClaudeCodeModel(resultsDir);
  } else if (agent === Agents.CODEX_CLI) {
    return extractCodexCliModel(resultsDir);
  }
  // JETSKI impl does not support trajectory pb parsing, leave model as unknown
  return 'unknown';
}

function extractErrorMessage(dir: string, targetFile: string): string {
  const failureFile = path.join(dir, 'generation_failed.json');
  if (fs.existsSync(failureFile)) {
    try {
      const failureInfo = JSON.parse(fs.readFileSync(failureFile, 'utf-8'));
      return `Generation failed: ${failureInfo.agentName} exited with ${failureInfo.exitCode}`;
    } catch (e) {
      return 'Generation failed (could not parse failure info)';
    }
  }

  const stderrPath = path.join(dir, 'agent_stderr.log');
  
  if (!fs.existsSync(stderrPath)) {
    return fs.existsSync(targetFile) ? 'Generation failed' : 'index.html not found';
  }

  return fs.readFileSync(stderrPath, 'utf8')
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.includes('YOLO mode'))
    .pop()?.slice(0, 100) || 'Generation mysteriously failed';
}

export function parseResultPath(relPath: string): { guide: string, taskName: string, runType: string } | null {
  const parts = relPath.split(path.sep);
  let guide: string, taskName: string, runType: string;
  
  if (parts.length === 2) {
    // [Legacy Fallback] Old structure: {taskName}/{runType}
    taskName = 'task';
    runType = parts[1];
    guide = parts[0].replace(/-task(-negative)?$/, '');
  } else if (parts.length >= 3) {
    [guide, taskName, runType] = parts;
  } else {
    return null;
  }
  
  return { guide, taskName, runType };
}

export async function collectResults(resultsDir: string, suiteConfig: SuiteConfig) {
  const taskMap = getTaskMap();

  const runDirs = fs.readdirSync(resultsDir)
    .filter(name => {
      const fullPath = path.join(resultsDir, name);
      return fs.statSync(fullPath).isDirectory() && /^\d+$/.test(name);
    })
    .sort((a, b) => parseInt(a) - parseInt(b));

  if (runDirs.length === 0) {
    throw new Error('No test runs found!');
  }

  // --- PASS 1: Generate parallel grader scripts for missing results ---
  const pnpmWorkspacePackages: string[] = [];
  const { spawnSync } = await import('child_process');

  for (const runDir of runDirs) {
    const runPath = path.join(resultsDir, runDir);
    // Support both legacy (*/guided) and new (*/*/guided) structures.
    // Avoid greedy **/guided to prevent matching nested folders generated by agents.
    const runTypeDirs = [
      ...glob.sync('*/guided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/*/guided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/unguided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/*/unguided', { cwd: runPath, absolute: true })
    ];

    for (const dir of runTypeDirs) {
      const relPath = path.relative(runPath, dir);
      const parsed = parseResultPath(relPath);
      if (!parsed) continue;
      const { guide, taskName, runType } = parsed;
      if (runType === 'base_app') continue; // Skip the base app setup folder
      const targetFile = path.join(dir, 'index.html');
      const targetPkgJson = path.join(dir, 'package.json');

      const taskInfo = taskMap.get(`${guide}/${taskName}`);
      if (!taskInfo) continue;

      const graderPath = path.join(taskInfo.guideDir, 'grader.ts');
      const graderResults = path.join(dir, `${guide}_results.json`);

      const targetAppExists = isTargetAppPresent(targetFile, targetPkgJson);

      const failureFile = path.join(dir, 'generation_failed.json');
      // If grader is missing, generation failed, target file is missing, or results already exist, skip generating a runner.
      if (!fs.existsSync(graderPath) || fs.existsSync(failureFile) || !targetAppExists || fs.existsSync(graderResults)) {
        continue;
      }

      // Generate a runner script to be picked up by pnpm -r run-grader
      // We import runPlaywright directly from the guides code to leverage existing test execution logic
      const gradeScript = getGraderScriptContent(dir, graderPath, guide);
      const relativeId = path.relative(resultsDir, dir); // e.g. "1/guideName/guided"
      fs.writeFileSync(path.join(dir, 'grade.mjs'), gradeScript);
      let pkgJsonObj: any = {
        name: `${guide.substring(0, 30)}-${runType}-grader`,
        type: "module",
        scripts: {}
      };
      if (fs.existsSync(targetPkgJson)) {
        try {
          pkgJsonObj = JSON.parse(fs.readFileSync(targetPkgJson, 'utf-8'));
          if (!pkgJsonObj.scripts) pkgJsonObj.scripts = {};
        } catch (e) {
          console.warn("Failed to parse existing package.json, overwriting...");
        }
      }
      pkgJsonObj.scripts["run-grader"] = `node grade.mjs --id ${relativeId}`;
      fs.writeFileSync(targetPkgJson, JSON.stringify(pkgJsonObj, null, 2));

      pnpmWorkspacePackages.push(relativeId);
    }
  }

  // --- PASS 1.5: Execute the accumulated grading runs in parallel ---
  if (pnpmWorkspacePackages.length > 0) {
    console.log(`\n>>> Discovered ${pnpmWorkspacePackages.length} un-graded tasks. Running parallel grading with pnpm -r run-grader...`);
    const pnpmWorkspacePath = path.join(resultsDir, 'pnpm-workspace.yaml');
    fs.writeFileSync(pnpmWorkspacePath, 'packages:\n  - \'**\'\n');
    try {
      spawnSync('pnpm', ['-r', 'run-grader'], { cwd: resultsDir, stdio: 'inherit' });
    } finally {
      if (fs.existsSync(pnpmWorkspacePath)) {
        fs.unlinkSync(pnpmWorkspacePath);
      }
    }
    console.log(`✅ Completed parallel grading pass\n`);
  }

  // --- PASS 2: Collect all results and formulate the report ---
  const allResults: Record<string, any[]> = {};

  for (const runDir of runDirs) {
    const runPath = path.join(resultsDir, runDir);

    // Support both legacy (*/guided) and new (*/*/guided) structures.
    // Avoid greedy **/guided to prevent matching nested folders generated by agents.
    const runTypeDirs = [
      ...glob.sync('*/guided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/*/guided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/unguided', { cwd: runPath, absolute: true }),
      ...glob.sync('*/*/unguided', { cwd: runPath, absolute: true })
    ];

    for (const dir of runTypeDirs) {
      const relPath = path.relative(runPath, dir);
      const parsed = parseResultPath(relPath);
      if (!parsed) continue;
      const { guide, taskName, runType } = parsed;
      if (runType === 'base_app') continue; // Skip the base app setup folder
      let guidesUsedResult: string[] = [];
      let retrievedGuides: string[] = [];
      let fileReadGuides: string[] = [];
      let guidanceToolsUsedResult: string[] = [];

      if (runType === 'guided') {
        const serving = suiteConfig.serving;
        const usage = await collectGuidesUsed(dir, serving, suiteConfig.agent);
        retrievedGuides = usage.retrievedGuides;
        fileReadGuides = usage.fileReadGuides;
        guidesUsedResult = [...new Set([...retrievedGuides, ...fileReadGuides])];
        guidanceToolsUsedResult = await collectGuidanceToolsUsed(dir, serving, suiteConfig.agent);
      }

      const targetFile = path.join(dir, 'index.html');
      const targetPkgJson = path.join(dir, 'package.json');
      const taskInfo = taskMap.get(`${guide}/${taskName}`);
      if (!taskInfo) {
        console.warn(`Skipping grading: Task ${guide} not found in task map`);
        continue;
      }

      let taskCategory = path.basename(path.dirname(taskInfo.guideDir));
      const isSkill = taskCategory === 'guides';
      let expectedToolPrefixes = ['modern-web'].filter(Boolean);
      if (isSkill) {
        taskCategory = path.basename(taskInfo.guideDir);
        expectedToolPrefixes = [taskCategory].filter(Boolean);
      }

      const graderPath = path.join(taskInfo.guideDir, 'grader.ts');
      let scenarioResults: any[] = [];
      const graderResults = path.join(dir, `${guide}_results.json`);

      const targetAppExists = isTargetAppPresent(targetFile, targetPkgJson);

      if (!fs.existsSync(graderPath)) {
        console.warn(`Grader not found for ${guide} at ${graderPath}`);
        scenarioResults.push({ name: 'Configuration', status: 'fail', message: 'Grader not found' });
      } else if (!targetAppExists) {
        scenarioResults.push({ name: 'File Check', status: 'fail', message: 'Target app missing' });
      } else if (!fs.existsSync(graderResults)) {
        const errorMessage = extractErrorMessage(dir, targetFile);
        scenarioResults.push({ passed: false, message: errorMessage, isEarlyFailure: true });
      } else {
        try {
          let json: any = null;

          if (fs.existsSync(graderResults)) {
            try {
              json = JSON.parse(fs.readFileSync(graderResults, 'utf-8'));
            } catch (e) {
              console.error(`Error parsing JSON results for ${guide} in ${dir}`, e);
            }
          } else {
            console.error(`Missing grader results JSON for ${guide} in ${dir}`);
          }

          if (json && json.suites && json.suites.length > 0) {
            const specs: any[] = [];
            const traverse = (suite: any) => {
              if (suite.specs) specs.push(...suite.specs);
              if (suite.suites) suite.suites.forEach(traverse);
            };
            json.suites.forEach(traverse);

            scenarioResults = specs.map((spec: any) => {
              const lastResult = spec.tests[0].results[spec.tests[0].results.length - 1];
              return {
                passed: lastResult.status === 'passed',
                message: spec.title,
                testId: spec.id
              };
            });
          }
        } catch (err: any) {
          console.error(`Error processing results for ${dir}:`, err);
          scenarioResults.push({ name: 'System Error', status: 'fail', message: err.message });
        }
      }

      const testName = `${taskName} - ${guide} - ${runType}`;
      const actualBaseApp = taskInfo.baseApp;

      let totalTokens = 0;
      let cachedTokens = 0;
      let hasTokenData = false;

      try {
        const files = fs.readdirSync(dir);
        
        // Gemini sessions
        const geminiSessions = files.filter(f => f.startsWith('session-') && f.endsWith('.json'));
        for (const file of geminiSessions) {
          const filePath = path.join(dir, file);
          const content = fs.readFileSync(filePath, 'utf8');
          const session = JSON.parse(content);
          if (session.messages) {
            const messagesWithTokens = session.messages.filter((m: any) => m.tokens);
            const lastMsg = messagesWithTokens[messagesWithTokens.length - 1];
            if (lastMsg) {
              totalTokens += lastMsg.tokens.total || 0;
              cachedTokens += lastMsg.tokens.cached || 0;
              hasTokenData = true;
            }
          }
        }

        // JSONL sessions (Codex or Claude Code)
        const jsonlSessions = files.filter(f => f.startsWith('session-') && f.endsWith('.jsonl'));
        for (const file of jsonlSessions) {
          const filePath = path.join(dir, file);
          const content = fs.readFileSync(filePath, 'utf8');
          const lines = content.split('\n');
          let lastTokenCount = 0;
          let lastCachedTokens = 0;
          let fileHasCodexTokens = false;
          let claudeTokens = 0;
          let claudeCachedTokens = 0;
          let fileHasClaudeTokens = false;
          
          for (const line of lines) {
            const trimmedLine = line.trim();
            if (!trimmedLine) continue;
            try {
              const obj = JSON.parse(trimmedLine);
              // Codex format (direct)
              if (obj.type === 'token_count' && obj.info && obj.info.total_token_usage) {
                lastTokenCount = obj.info.total_token_usage.total_tokens || 0;
                lastCachedTokens = obj.info.total_token_usage.cached_input_tokens || 0;
                fileHasCodexTokens = true;
              }
              // Codex format (payload)
              if (obj.type === 'event_msg' && obj.payload && obj.payload.type === 'token_count' && obj.payload.info && obj.payload.info.total_token_usage) {
                lastTokenCount = obj.payload.info.total_token_usage.total_tokens || 0;
                lastCachedTokens = obj.payload.info.total_token_usage.cached_input_tokens || 0;
                fileHasCodexTokens = true;
              }
              // Claude Code format
              if (obj.message && obj.message.usage) {
                claudeTokens += (obj.message.usage.output_tokens || 0) + (obj.message.usage.input_tokens || 0);
                claudeCachedTokens += obj.message.usage.cache_read_input_tokens || 0;
                fileHasClaudeTokens = true;
              }
            } catch (e) {
              // Ignore parse errors
            }
          }
          if (fileHasCodexTokens) {
            totalTokens += lastTokenCount;
            cachedTokens += lastCachedTokens;
            hasTokenData = true;
          } else if (fileHasClaudeTokens) {
            totalTokens += claudeTokens;
            cachedTokens += claudeCachedTokens;
            hasTokenData = true;
          }
        }
      } catch (e) {
        console.error(`Failed to extract token usage in ${dir}:`, e);
      }

      if (!allResults[testName]) {
        allResults[testName] = [];
      }
      allResults[testName].push({
        runNumber: parseInt(runDir),
        results: scenarioResults,
        guidesUsed: guidesUsedResult,
        retrievedGuides: retrievedGuides,
        fileReadGuides: fileReadGuides,
        guidanceToolsUsed: guidanceToolsUsedResult,
        discipline: taskCategory,
        isSkill: isSkill,
        expectedToolPrefixes: expectedToolPrefixes,
        guideName: guide,
        taskName: taskName,
        baseApp: actualBaseApp,
        prompt: taskInfo.prompt,
        files: fs.readdirSync(dir).filter(f => !fs.statSync(path.join(dir, f)).isDirectory()),
        tokenUsage: hasTokenData ? { total: totalTokens, cached: cachedTokens } : undefined
      });
    }
  }

  let estimatedRuntime: number | undefined = undefined;
  const evalsJsonPath = path.join(resultsDir, 'evals.json');
  if (fs.existsSync(evalsJsonPath)) {
    try {
      const evalsContent = fs.readFileSync(evalsJsonPath, 'utf-8');
      const timestampMatch = evalsContent.match(/"timestamp":\s*"([^"]+)"/);
      
      let startTimestamp: Date | null = null;
      if (timestampMatch) {
        startTimestamp = new Date(timestampMatch[1]);
      } else {
        const logPath = path.join(resultsDir, 'test_suite.log');
        if (fs.existsSync(logPath)) {
          const logContent = fs.readFileSync(logPath, 'utf-8');
          const firstLineMatch = logContent.match(/\[LOG\s([^\]]+)\]/);
          if (firstLineMatch) {
            startTimestamp = new Date(firstLineMatch[1]);
          }
        }
      }

      if (startTimestamp) {
        const endTimestamp = fs.statSync(evalsJsonPath).mtime;
        estimatedRuntime = endTimestamp.getTime() - startTimestamp.getTime();
      }
    } catch (e) {
      console.error('Failed to estimate runtime during collection:', e);
    }
  }

  return { allResults, numRuns: runDirs.length, totalRuntime: estimatedRuntime };
}
