name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  basics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Preflight (Typecheck, Lint, Tests)
        run: pnpm run preflight

      # Fail if any changes were written to any source files or generated untracked files
      - run: git add -A && git diff --cached --exit-code

      #  TODO(paulirish): restore this after fixing:
      #      fatal: You are not currently on a branch. To push the history leading to the current (detached HEAD) state now, use git push origin HEAD:<name-of-remote-branch>       
      #
      # - name: Generate guides diagram and commit
      #   run: |
      #     node scripts/guide-features-diagram.mjs
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add guides/features-and-use-cases.md
      #     git commit -m "Auto-generate features-and-use-cases.md" || echo "No changes to commit"
      #     git push

  browser:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm run setup:playwright --with-deps

      - name: Playwright E2E Tests
        run: pnpm --filter eval-view run test:e2e
